"""

Revision ID: 73b4aa386d61
Revises: 501e741ce151
Create Date: 2025-10-07 20:21:10.831422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b4aa386d61'
down_revision: Union[str, None] = '501e741ce151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('provider', sa.String(length=64), nullable=False))
    op.add_column('messages', sa.Column('instrument', sa.String(length=32), nullable=False))
    op.add_column('messages', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('max_tokens', sa.Integer(), nullable=True))
    op.drop_column('messages', 'ai_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ai_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('messages', 'max_tokens')
    op.drop_column('messages', 'temperature')
    op.drop_column('messages', 'instrument')
    op.drop_column('messages', 'provider')
    # ### end Alembic commands ###
